package igu;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author RAFAEL
 */
public class Menu extends javax.swing.JFrame {

    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/fondoEscolar.png"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        api = new javax.swing.JMenu();
        alumno = new javax.swing.JMenuItem();
        aMateria = new javax.swing.JMenuItem();
        dCliente = new javax.swing.JMenuItem();
        jReporte = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.orange);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));
        escritorio.setRequestFocusEnabled(false);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        api.setText("Aplicaciones");
        api.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apiActionPerformed(evt);
            }
        });

        alumno.setText("Agregar Alumno");
        alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoActionPerformed(evt);
            }
        });
        api.add(alumno);

        aMateria.setText("Agregar Materia");
        aMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMateriaActionPerformed(evt);
            }
        });
        api.add(aMateria);

        dCliente.setText("Inscripcion de Materias");
        dCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dClienteActionPerformed(evt);
            }
        });
        api.add(dCliente);

        jReporte.setText("Reporte de materias");
        jReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReporteActionPerformed(evt);
            }
        });
        api.add(jReporte);

        jMenuBar1.add(api);

        salir.setText("Salir");

        jMenuItem1.setText("Salir del sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        salir.add(jMenuItem1);

        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        Menu m1 = new Menu();
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }

    private void alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarAlumno a = new AgregarAlumno();
        escritorio.add(a);
        escritorio.moveToFront(a);
    }//GEN-LAST:event_alumnoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarMateria m = new AgregarMateria();
        escritorio.add(m);
        escritorio.moveToFront(m);
    }//GEN-LAST:event_aMateriaActionPerformed

    private void dClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InscribirMateria i = new InscribirMateria();
        escritorio.add(i);
        escritorio.moveToFront(i);
    }//GEN-LAST:event_dClienteActionPerformed

    private void apiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_apiActionPerformed

    private void jReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReporteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MostrarMateria m = new MostrarMateria();
        escritorio.add(m);
        escritorio.moveToFront(m);
    }//GEN-LAST:event_jReporteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aMateria;
    private javax.swing.JMenuItem alumno;
    private javax.swing.JMenu api;
    private javax.swing.JMenuItem dCliente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jReporte;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
